name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - run: npm install --frozen-lockfile
    - run: npm run ci:all
    - run: npm --cwd ./packages/backend lint

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - run: npm install --frozen-lockfile
    - run: npm run ci:all
    - run: npm --cwd ./packages/frontend lint

  typecheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        workspace:
        - backend
        - misskey-js
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-node@v4.0.2
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - run: corepack enable
    - run: npm install --frozen-lockfile
    - run: npm run ci:all
      if: ${{ matrix.workspace == 'backend' }}
    - run: pnpm --filter ${{ matrix.workspace }} run typecheck
