name: Test (production install and build)

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  NODE_ENV: production

jobs:
  production:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version-file: '.node-version'

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --frozen-lockfile
    - run: npm run ci:all
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config/default.yml
    - name: Build
      run: npm run build
